### ISSUE TITLE
repo owner is gay

### ISSUE THREAD

**Issue by cipher416** [felixgoz/is-odd-react#4]
Bro, why did you delete all my code? Imagine if your bank uses my code, and when I merge it, a bug causes a bank run, leading to the collapse of the entire world economy. I hope you make wiser decisions next time.

_Originally posted by @felixgoz in https://github.com/felixgoz/is-odd-react/issues/2#issuecomment-2499597283_

**Comment by felixgoz** [comment]
I'm not gay, I'm a guy.
