### ISSUE TITLE
are you stupid with a lore reason?

### ISSUE THREAD

**Issue by brandon-julio-t** [felixgoz/is-odd-react#5]
dear officer balls,

why did you close my PR (https://github.com/felixgoz/is-odd-react/pull/2) ? are you stupid? is there a lore reason for this?

![image](https://github.com/user-attachments/assets/acbeb07e-b95a-4c80-b57f-7dde4b039784)

**Comment by cipher416** [comment]
![images](https://github.com/user-attachments/assets/adda054a-5e45-4136-8727-348fa177ee6d)

is bro stupid?

**Comment by felixgoz** [comment]
Thank you for your input. You guys need a therapist ASAP.
